### ISSUE TITLE
FR: Search and retrieve from wikidata based on note title

### ISSUE THREAD

**Issue by brimwats** [samwho/obsidian-wikidata-importer#1]
Would be nice to not have to search WD for the ID and to search from note

**Comment by samwho** [comment]
This crossed my mind too. I avoided it at the time because sometimes you can get multiple entities with the same name (e.g. "Windows"), but it would be possible to show a choice dialog when this happens.

Thanks for the FR! I can't make any promises on when I'll get around to it but I will do my best.
